# Use an official Node.js image
FROM node:20.17-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --omit-dev

RUN npm audit fix --force

COPY . .

# Define build arguments
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG MONGO_URI
ARG NEXT_PUBLIC_ECB_API_URL
ARG DB_NAME
ARG UPDATE_TOKENS_ENDPOINT

RUN npm run build

ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV MONGO_URI=${MONGO_URI}
ENV NEXT_PUBLIC_ECB_API_URL=${NEXT_PUBLIC_ECB_API_URL}
ENV DB_NAME=${DB_NAME}
ENV UPDATE_TOKENS_ENDPOINT=${UPDATE_TOKENS_ENDPOINT}

EXPOSE 3000

CMD ["npm", "start"]