#!/bin/bash

# Define repository URL and the directory where the repository will be cloned
REPO_URL="https://github.com/somadina6/cryptovision-ai-app.git"
APP_DIR="/var/www/html/cryptovision-ai-app"

# Navigate to the parent directory
cd /var/www/html || { echo "Failed to change directory";  }

# Remove the existing application directory
rm -rf "$APP_DIR"

# Clone the repository afresh
git clone "$REPO_URL" "$APP_DIR" || { echo "Failed to clone repository";  }

# Navigate to the application directory
cd "$APP_DIR" || { echo "Failed to change directory";  }

// Copy the .env file to the application directory
cp /home/node/.env /var/www/html/cryptovision-ai-app/.env

# Install any new dependencies
npm install || { echo "Failed to install dependencies"; }


# Build the application if necessary
npm run build && echo "Build successful" || { echo "Build failed"; }


pm2 stop crypto-app || { echo "Failed to stop PM2 process"; }

# Optionally, remove the existing PM2 process
pm2 delete crypto-app || { echo "Failed to delete PM2 process"; }

# Start the PM2 process
sudo pm2 start npm --name "crypto-app" -- start || { echo "Failed to start PM2 process"; }

# Optionally, save the PM2 process list
pm2 save || { echo "Failed to save PM2 process list";  }

echo "Deployment complete and PM2 process restarted."
