name: Build DB Update Container

on:
  push:
    branches:
      - develop

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.updateTokens
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cryptovision-db-update:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cryptovision-db-update:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cryptovision-db-update:cache,mode=max
          build-args: |
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

  deploy:
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ""
          port: 22
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/cryptovision-db-update:latest

            # Stop and remove existing container
            docker stop db-update || true
            docker rm db-update || true

            # Run new container with environment variables
            docker run -d --name db-update \
              -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
              -e SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} \
              ${{ secrets.DOCKER_USERNAME }}/cryptovision-db-update:latest
