name: CryptoVision CI/CD
run-name: Build and push Docker image ${{ github.run_number }}
on:
  push:
    branches:
      - main
jobs:
  Install-And-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cryptovision:latest
            ${{ secrets.DOCKER_USERNAME }}/cryptovision:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cryptovision:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cryptovision:cache,mode=max
          build-args: |
            GOODLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
            MONGO_URI=${{ secrets.MONGO_URI }}
            NEXT_PUBLIC_ECB_API_URL=${{ secrets.NEXT_PUBLIC_ECB_API_URL }}
            DB_NAME=${{ secrets.DB_NAME }}
            UPDATE_TOKENS_ENDPOINT=${{ secrets.UPDATE_TOKENS_ENDPOINT }}
